server:
  port: 8202

spring:
  application:
    name: adrian-server-test
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: adrian
        password: 123456
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://adrian:123456@localhost:8001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true


#logging:
#  level:
#    org.springframework.security: DEBUG


info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always